### ISSUE TITLE
[WIP] Add end-to-end ML deployment workshop to Operate First

### ISSUE THREAD

**Issue by isabelizimm** [operate-first/support#107]
**Describe the solution you'd like:**
I would be interested in having this workshop[1] live on Operate First 
[1] https://github.com/aicoe-aiops/pet-image-detection

**Workshop description: EDITED TO IMAGE DETECTION WS** 
This repository has materials from a  tutorial on machine learning model serving workflows and using OpenShift and Seldon. The goal of this workshop is to get developers comfortable with some of the habits, concerns, and practices necessary to effectively incorporate model serving into their workflow. One notable aspect of the lab is that it also integrates model explainability tactics to further explore why the model is not performing as expected.

**Additional context:**
This doubles as me learning about Operate First use cases and capabilities while adding content to Operate First workshops. I plan to give ease of contributing feedback from a "Level 0" contributor perspective. 🙂

**Comment by HumairAK** [comment]
Hello @isabelizimm -- welcome! We will definitely try to get you started, but I think we'll need a bit more information about what your needs are.  

>  I would be interested in having this workshop[1] live on Operate First 

Can you expand on what you mean by 'live on Operate First' ? For example, do you need to deploy this app on an openshift environment?

If this is the case we'll need to get you set up with a namespace with the appropriate access. Let us know!

**Comment by isabelizimm** [comment]
Thank you for the warm welcome! 

I'm hoping to have this workshop deployed so when it is used for demos, any MOC user can access it. I had originally imagined it would exist similar to the `ml-prague-2021` notebook dropdown on JH. However, if it's easier to have a designated namespace for the app, I am okay with that solution as well!

**Comment by tumido** [comment]
I think you kinda want both. You want the image to be usable in the JupyterHub - therefore it will be added like this:
https://www.operate-first.cloud/users/data-science-workflows/docs/create_and_deploy_jh_image.md#adding-the-image-where-you-need-it
Against this directory:
https://github.com/operate-first/apps/tree/master/odh/base/jupyterhub/notebook-images

And for the rest, like your `Service` and `Route` and such, you'd probably need to have a separate namespace, since we'd like to keep the JupyterHub namespace just for the notebook servers and ideally nothing else.

Would something like that work for you?

**Comment by isabelizimm** [comment]
That sounds like a good way to break everything down!

**Comment by HumairAK** [comment]
@isabelizimm  do you already have an image available? If not then the [link that Tom](https://www.operate-first.cloud/users/data-science-workflows/docs/create_and_deploy_jh_image.md#adding-the-image-where-you-need-it) has added above shows you the instructions for buildling/pushing your image.

Once you have an image, you can link it here and we can add the appropriate image stream to [this location](https://github.com/operate-first/apps/tree/master/odh/base/jupyterhub/notebook-images) so that it may show up on JH. Or you can make a PR and add this imagestream yourself. The doc (step 2) show you how to create it. 

For the namespace, what should the namespace be called? We will add you to the data-science group (if you aren't already there) and give this group access to the namespace with admin privileges, so you can use it as needed.

**Comment by isabelizimm** [comment]
I'll work on the image and make a PR! Per the namespace, `ws-ml-workflows` or `ds-ml-workflows-ws` are both good with me.

**Comment by HumairAK** [comment]
@isabelizimm 

Have you logged in to the MOC cluster yet? https://console-openshift-console.apps.cnv.massopen.cloud/ 

If not -- can you? You can use the sso option and any gmail account (e.g. your redhat email). This will automatically create a user for you. 

Once done, can you give send either myself or @tumido / @4n4nd  your user id via private dm/email? (this will be the email you used to login) -- we will use this to give you the appropriate access.

**Comment by HumairAK** [comment]
The namespace + user was created/onboarded. All that's left now is the imagestream to add to JH.

**Comment by isabelizimm** [comment]
Imagestream was added to JH. Thanks all!
