### ISSUE TITLE
Instance of Prometheus Pushgateway on Zero cluster

### ISSUE THREAD

**Issue by anishasthana** [operate-first/support#114]
The [Prometheus Pushgateway](https://github.com/prometheus/pushgateway) provides a great way for short-lived jobs to push metrics to Prometheus for longer term analysis. What are your thoughts about including it in the stack for the Zero cluster?

**Comment by 4n4nd** [comment]
we don't have a pushgateway instance is because I think it will be difficult to have a single instance of pushgateway available for the public to use and manage labels for every service that pushes metrics to this gateway. 
The Thoth team (@harshad16) had a similar requirement and I suggested them to deploy their own instance of pushgateway in one of the thoth namespaces and add a servicemonitor that scrapes the pushgateway in the operatefirst monitoring namespace.

**Comment by anishasthana** [comment]
manage labels in what sense? Shouldn't all metrics that are pushed already have their associated labels?

**Comment by 4n4nd** [comment]
By manage labels I mean we won't have any control over who pushes metrics to a specific label.
For example, label: `{job="A"}`, anyone who had access to the url would be able to push metrics for that job label.

**Comment by anishasthana** [comment]
That makes sense. @Jooho I'll let you make a call on how you want to proceed :-)

**Comment by 4n4nd** [comment]
You could request for a namespace in operate-first and deploy an instance of pushgateway where only you would push metrics and these would be scraped by the operate-first Prometheus.

**Comment by Jooho** [comment]
I requested and I got namespace! 

Thanks!

You can close it

**Comment by HumairAK** [comment]
Thanks @Jooho -- closing.
