### ISSUE TITLE
No external route to access object storage buckets of storageclass `ocs-storagecluster-ceph-rgw	`

### ISSUE THREAD

**Issue by 4n4nd** [operate-first/support#123]
**Is your feature request related to a problem? Please describe.**
ObjectBucketClaims like `black-flake` are accessible only from inside the operate-first cluster using the following host: 
 http://rook-ceph-rgw-ocs-storagecluster-cephobjectstore.openshift-storage.svc.cluster.local

**Describe the solution you'd like**
Create a Route for [this service](https://console-openshift-console.apps.zero.massopen.cloud/k8s/ns/openshift-storage/services/rook-ceph-rgw-ocs-storagecluster-cephobjectstore) so that the buckets are accessible externally.

/cc @Shreyanand

**Comment by tumido** [comment]
@4n4nd or @Shreyanand if you want to access a bucket externally, please change your bucket claim storage class (you'd need to delete and recreate the bucket) to `openshift-storage.noobaa.io`. That will allow you to use this external route:

https://s3-openshift-storage.apps.zero.massopen.cloud/

We won't be exposing internal ceph, since that is not supported by OCS operator.

We've recently updated our docs advising users to use this storage class, we think it should lower the confusion and cause less troubles:

https://github.com/operate-first/support/blob/main/docs/claiming_object_store.md

**Comment by tumido** [comment]
Closing as wontfix
