### ISSUE TITLE
[TASK] Better wording for the README explaining MOC vs OperateFirst vs ODH

### ISSUE THREAD

**Issue by tumido** [operate-first/support#124]
**User story**
Heidi:
> There is onboarding to use the MOC, and then there is onboarding to use the Operate First environment.  Then there is onboarding that uses the ODH operator within Operate First.  But you don't have to be part of ODH to use the Operate First environment.

@tumido:
> yeah... that makes sense. Thank you! ￼  We definitely need to clarify that Operate First is just one of many projects running in MOC and Operate First's deployment of ODH (which is an upstream project and we just deploy+manage it) is just one (user facing) workload or many run by Operate First... I'm gonna try wording it better for the Operate first user support page...

**Additional context**
https://chat.google.com/room/AAAAAYpDdc8/QZOVRVz6olM

**Acceptance Criteria**
- [ ] Updated README.md

**Comment by HumairAK** [comment]
When we first started, helping manage operations on the moc clusters wasn't our intended goal. So we named everything with the operate-first labels (e.g. opf-<odh-component>), that was mostly gitops related to services specifically we'll be deploying -- and not gitops for environments (e.g. moc clusters). But now we work much more closely with infrastructure as one team, and so we've included environment/cluster management within our repos as well. This has resulted in: 

- Apps deployed on moc that we consider "operate-first" apps, like ODH, Observatorium, these are sometimes prefixed as opf-<odh-component>, and organized under `operate-first` groups (like in argocd). 
- Environments/Clusters managed by operate-first initiative 

This results in confusing wording, phrasing, and confusion because you have "operate-first managed apps on environments like moc" and then you have "moc clusters managed by operate-first initiative/repos/team/etc.". 

I don't have a clear solution, but I think we should think about rebranding one of those things and renaming some stuff to draw clear distinctions.

**Comment by HumairAK** [comment]
So a few steps we intend to take to clarify the distinctions: 

- https://github.com/operate-first/apps/issues/466#issuecomment-815057592
- https://github.com/operate-first/blueprint/issues/62#issuecomment-814919133

**Comment by HumairAK** [comment]
Site updated with clearer distinctions between MOC and Operate-First. https://github.com/operate-first/operate-first.github.io/pull/238

**Comment by HumairAK** [comment]
I think the distinction is relatively clear now with the various updates to the site / readme's etc. If anyone feels different please re-open this explaining what else can be improved.
