### ISSUE TITLE
How to add extensions in JH with Elyra images

### ISSUE THREAD

**Issue by Shreyanand** [operate-first/support#143]
**Describe the bug**
I tried to add a spell check extension to the Elyra image on JH but got into the error in the screenshot. Is there a workaround this?

**To Reproduce**
1. Go to Operate First JH instance
2. Spawn a notebook with Elyra v0.0.5
3. Click on extensions and install any extension

**Expected behaviour**
I expect the extension to be added to the environment.

**Screenshots**
![Screenshot from 2021-03-18 15-10-50](https://user-images.githubusercontent.com/8916126/112054029-15eca280-8b7b-11eb-80e2-1ed1082872cf.png)

**Comment by tumido** [comment]
I honestly have no idea. It may be better to direct this to our JupyterLab/ODH experts on this

cc @pacospace @vpavlin , can you please help? I'm clueless..

**Comment by pacospace** [comment]
Hi @Shreyanand,

To install extensions in jupyterlab you need to consider few things.

- there are two types of jupyterlab extensions at the moment due to API version

- most of the extensions with API jupyterlab < 3.0 requires compilation of the code when creating an image.
For example. Elyra https://github.com/opendatahub-io/s2i-lab-elyra/blob/fbb209769b0ba04a43a041fd862315a9fa9fe7ad/.s2i/bin/assemble#L15

- From jupyterlab 3.0 this is no more a requirement. The API has been changed in a way that if you build jupyterlab 3.0 compliant extensions `jupyter lab build` is no more required and you can add an extension installing it with pip. 
For example jupyterlab-requirements is compliant and can be installed without rebuilding jupyterlab: https://github.com/thoth-station/jupyterlab-requirements

This approach should not be suggested though as we want to know which package versions (including extensions versions) are present in the image.
Therefore a better approach could be open an issue in https://github.com/thoth-station/s2i-minimal-notebook and we can help you adding a specific extension.

To conclude the steps to have new extensions are:

1. Check which jupyterlab version is used with the extension, if it is 2.0 or 3.0 compliant will lead to different approach to include them. (Be aware current Elyra is based on jupyterlab 3.0, therefore only jupyterlab 3.0 compliant extensions can be added, otherwise you need to request upstream for a new release).

2. Open issue in https://github.com/thoth-station/s2i-minimal-notebook if you want to support, you think this extension can benefit more data scientists or if you want this extension only for your specific project. Based on these requirements we can move forward.

If you have questions please reach out.

**Comment by pacospace** [comment]
> Hi @Shreyanand,
> 
> Are you trying to install the extension from jupyterlab UI using npm packages?
> 
> Are you referring to [1] extension?
> 
> To install extensions in jupyterlab you need to consider few things.
> 
> * there are two types of jupyterlab extensions at the moment due to API version
> * most of the extensions with API jupyterlab < 3.0 requires compilation of the code when adding new extension, especially if they are server extensions that need to be discovered by jupyterlab API.
>   For example. Elyra https://github.com/opendatahub-io/s2i-lab-elyra/blob/fbb209769b0ba04a43a041fd862315a9fa9fe7ad/.s2i/bin/assemble#L15
> * From jupyterlab 3.0 this is no more a strong constraint. The API has been changed in a way that if you build jupyterlab 3.0 compliant extensions `jupyter lab build` is no more required and you can add an extension installing it with pip.
>   For example jupyterlab-requirements is compliant and can be installed without rebuilding jupyterlab: https://github.com/thoth-station/jupyterlab-requirements
> 
> Please keep in mind that in general we want to know which package versions (including extensions versions) are present in the image.
> Therefore a better approach could be open an issue in https://github.com/thoth-station/s2i-minimal-notebook and we can help you adding a specific extension.
> 
> To summarize I think the steps to have new extensions can be:
> 
> 1. Check which jupyterlab version is used with the extension, if it is 2.0 or 3.0 compliant will lead to different approach to include them. (Be aware current Elyra is based on jupyterlab 3.0, therefore only jupyterlab 3.0 compliant extensions can be added, otherwise you need to request upstream for a new release).
> 2. Open issue in https://github.com/thoth-station/s2i-minimal-notebook if you want to support, you think this extension can benefit more data scientists or if you want this extension only for your specific project. Based on these requirements we can move forward.
> 3. New release of Elyra jupyterlab image needs to be created with new base image. cc @vpavlin
> 
> if [1] is the extension you need, it is jl 3.0 compatible so we can add it to the base image for jupyterlab so that all DS can benefit from it. wdyt?
> 
> If you have questions please reach out.
> 
> References:
> 
> * [1] https://github.com/jupyterlab-contrib/spellchecker

@tumido @goern @durandom @harshad16 do we have a section in Operate First docs to describe, how to propose/request a new package ithat can be added to base images?

**Comment by pacospace** [comment]
> **Describe the bug**
> I tried to add a spell check extension to the Elyra image on JH but got into the error in the screenshot. Is there a workaround this?
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Go to Operate First JH instance
> 2. Spawn a notebook with Elyra v0.0.5
> 3. Click on extensions and install any extension
> 4. See error
> 
> **Expected behaviour**
> I expect the extension to be added to the environment.
> 
> **Screenshots**
> ![Screenshot from 2021-03-18 15-10-50](https://user-images.githubusercontent.com/8916126/112054029-15eca280-8b7b-11eb-80e2-1ed1082872cf.png)

Other comment, I just noticed you are using Elyra image v0.0.5 from operate first, this is based on old Elyra < 2, therefore jupyterlab 2.0 version. Try spawning Elyra v0.0.6 image which is Elyra 2.0 and jupyterlab 3.0 compliant with jupyterlab-requirements also. If you try installing there a jupyterlab 3.0 compliant extension and reload you should see the new extension available.

@tumido @vpavlin @goern @durandom what is the rule for keeping versions? Having Elyra v0.0.5 and Elyra v0.0.6 for users might be confusing and not helping, especially if they don't find descriptions about the packages in those versions. Do we have a place where these images are described more into details? or at least changing the tag maybe to say one is elyra <2 jupyterlab 2 version, while the other is elyra 2.* jupyterlab 3.* compliant.
Or we can simply remove old tag instead of keeping both versions of the same image.

wdyt?

**Comment by pacospace** [comment]
> > **Describe the bug**
> > I tried to add a spell check extension to the Elyra image on JH but got into the error in the screenshot. Is there a workaround this?
> > **To Reproduce**
> > Steps to reproduce the behavior:
> > 
> > 1. Go to Operate First JH instance
> > 2. Spawn a notebook with Elyra v0.0.5
> > 3. Click on extensions and install any extension
> > 4. See error
> > 
> > **Expected behaviour**
> > I expect the extension to be added to the environment.
> > **Screenshots**
> > ![Screenshot from 2021-03-18 15-10-50](https://user-images.githubusercontent.com/8916126/112054029-15eca280-8b7b-11eb-80e2-1ed1082872cf.png)
> 
> Other comment, I just noticed you are using Elyra image v0.0.5 from operate first, this is based on old Elyra < 2, therefore jupyterlab 2.0 version. Try spawning Elyra v0.0.6 image which is Elyra 2.0 and jupyterlab 3.0 compliant with jupyterlab-requirements also. If you try installing there a jupyterlab 3.0 compliant extension and reload you should see the new extension available.

@tumido @vpavlin @goern @durandom what is the rule for keeping versions? Having Elyra v0.0.5 and Elyra v0.0.6 for users might be confusing and not helping, especially if they don't find descriptions about the packages in those versions. Do we have a place where these images are described more into details? or at least changing the tag maybe to say one is elyra <2 jupyterlab 2 version, while the other is elyra 2.* jupyterlab 3.* compliant.
Or we can simply remove old tag instead of keeping both versions of the same image.

wdyt?

**Comment by tumido** [comment]
@pacospace I think we can turn that into an RFE for JH spawner. It would be nice if you can see some (rich? markdown with links?) description to the images (possibly listing the components and so on) here:
![image](https://user-images.githubusercontent.com/7453394/112137612-c1741200-8bd0-11eb-8b78-e8de37d71fff.png)

Similarly to the size tooltip:
![image](https://user-images.githubusercontent.com/7453394/112137657-cfc22e00-8bd0-11eb-8661-83fcb7cde93a.png)

I know this would have to be OpenShift specific, because ImageStreams are OpenShift only. @pacospace @vpavlin do you know where would be the best place to file an RFE issue for it?

**Comment by pacospace** [comment]
> @pacospace I think we can turn that into an RFE for JH spawner. It would be nice if you can see some (rich? markdown with links?) description to the images (possibly listing the components and so on) here:
> ![image](https://user-images.githubusercontent.com/7453394/112137612-c1741200-8bd0-11eb-8b78-e8de37d71fff.png)
> 
> Similarly to the size tooltip:
> ![image](https://user-images.githubusercontent.com/7453394/112137657-cfc22e00-8bd0-11eb-8661-83fcb7cde93a.png)
> 
> I know this would have to be OpenShift specific, because ImageStreams are OpenShift only. @pacospace @vpavlin do you know where would be the best place to file an RFE issue for it?

I love this idea @tumido. Let's do it!!

**Comment by Shreyanand** [comment]
> Hi @Shreyanand,
> 
> Are you trying to install the extension from jupyterlab UI using npm packages?
> 
> Are you referring to [1] extension?
> 
> To install extensions in jupyterlab you need to consider few things.
> 
> * there are two types of jupyterlab extensions at the moment due to API version
> * most of the extensions with API jupyterlab < 3.0 requires compilation of the code when adding new extension, especially if they are server extensions that need to be discovered by jupyterlab API.
>   For example. Elyra https://github.com/opendatahub-io/s2i-lab-elyra/blob/fbb209769b0ba04a43a041fd862315a9fa9fe7ad/.s2i/bin/assemble#L15
> * From jupyterlab 3.0 this is no more a strong constraint. The API has been changed in a way that if you build jupyterlab 3.0 compliant extensions `jupyter lab build` is no more required and you can add an extension installing it with pip.
>   For example jupyterlab-requirements is compliant and can be installed without rebuilding jupyterlab: https://github.com/thoth-station/jupyterlab-requirements
> 

@pacospace I tried jupyterlab 3.0 (through Elyra v0.0.6) and I get the same error. Try going to the extension manager and searching for spell checker. It'll take you to the spell checker you attached [1]. If you install it from the UI it'll give the same rebuild error. If I do a pip install instead, it downloads the extension but I don't see it working in a notebook. Maybe I'm missing something here...

> Please keep in mind that in general we want to know which package versions (including extensions versions) are present in the image.
> Therefore a better approach could be open an issue in https://github.com/thoth-station/s2i-minimal-notebook and we can help you adding a specific extension.
> 
> To summarize I think the steps to have new extensions can be:
> 
> 1. Check which jupyterlab version is used with the extension, if it is 2.0 or 3.0 compliant will lead to different approach to include them. (Be aware current Elyra is based on jupyterlab 3.0, therefore only jupyterlab 3.0 compliant extensions can be added, otherwise you need to request upstream for a new release).
> 2. Open issue in https://github.com/thoth-station/s2i-minimal-notebook if you want to support, you think this extension can benefit more data scientists or if you want this extension only for your specific project. Based on these requirements we can move forward.
> 3. New release of Elyra jupyterlab image needs to be created with new base image. cc @vpavlin
> 
> if [1] is the extension you need, it is jl 3.0 compatible so we can add it to the base image for jupyterlab so that all DS can benefit from it. wdyt?

Oh I think that's a great idea. We could also add other common extensions. @chauhankaranraj feel free to add your preferences here.

> 
> If you have questions please reach out.
> 
> References:
> 
> * [1] https://github.com/jupyterlab-contrib/spellchecker

**Comment by pacospace** [comment]
> > Hi @Shreyanand,
> > Are you trying to install the extension from jupyterlab UI using npm packages?
> > Are you referring to [1] extension?
> > To install extensions in jupyterlab you need to consider few things.
> > 
> > * there are two types of jupyterlab extensions at the moment due to API version
> > * most of the extensions with API jupyterlab < 3.0 requires compilation of the code when adding new extension, especially if they are server extensions that need to be discovered by jupyterlab API.
> >   For example. Elyra https://github.com/opendatahub-io/s2i-lab-elyra/blob/fbb209769b0ba04a43a041fd862315a9fa9fe7ad/.s2i/bin/assemble#L15
> > * From jupyterlab 3.0 this is no more a strong constraint. The API has been changed in a way that if you build jupyterlab 3.0 compliant extensions `jupyter lab build` is no more required and you can add an extension installing it with pip.
> >   For example jupyterlab-requirements is compliant and can be installed without rebuilding jupyterlab: https://github.com/thoth-station/jupyterlab-requirements
> 
> @pacospace I tried jupyterlab 3.0 (through Elyra v0.0.6) and I get the same error. Try going to the extension manager and searching for spell checker. It'll take you to the spell checker you attached [1]. If you install it from the UI it'll give the same rebuild error. If I do a pip install instead, it downloads the extension but I don't see it working in a notebook. Maybe I'm missing something here...
> 
> > Please keep in mind that in general we want to know which package versions (including extensions versions) are present in the image.
> > Therefore a better approach could be open an issue in https://github.com/thoth-station/s2i-minimal-notebook and we can help you adding a specific extension.
> > To summarize I think the steps to have new extensions can be:
> > 
> > 1. Check which jupyterlab version is used with the extension, if it is 2.0 or 3.0 compliant will lead to different approach to include them. (Be aware current Elyra is based on jupyterlab 3.0, therefore only jupyterlab 3.0 compliant extensions can be added, otherwise you need to request upstream for a new release).
> > 2. Open issue in https://github.com/thoth-station/s2i-minimal-notebook if you want to support, you think this extension can benefit more data scientists or if you want this extension only for your specific project. Based on these requirements we can move forward.
> > 3. New release of Elyra jupyterlab image needs to be created with new base image. cc @vpavlin
> > 
> > if [1] is the extension you need, it is jl 3.0 compatible so we can add it to the base image for jupyterlab so that all DS can benefit from it. wdyt?
> 
> Oh I think that's a great idea. We could also add other common extensions. @chauhankaranraj feel free to add your preferences here.
> 
> > If you have questions please reach out.
> > References:
> > 
> > * [1] https://github.com/jupyterlab-contrib/spellchecker

hey @Shreyanand I installed it and it is working for me as described in the readme in [1], after a simple pip install. 

The installation through npm package from the UI might require always rebuild, but not the pip one from the terminal.

Try reloading the page and it shoud be available.

Please open an issue in https://github.com/thoth-station/s2i-minimal-notebook or better into https://github.com/opendatahub-io/s2i-lab-elyra so we can add those extensions by default, it might benefit ODH users upstream and downstream :)
