### ISSUE TITLE
GPU Supported in Operate First

### ISSUE THREAD

**Issue by pacospace** [operate-first/support#147]
**Is your feature request related to a problem? Please describe.**
As Operate First User (data scientist and/or devops),

I would like to use GPUs for my training or inference

**Describe the solution you'd like**
Having GPU and GPU Operator

**Describe alternatives you've considered**

**Additional context**

**Comment by tumido** [comment]
We don't have GPUs in the zero cluster neither we plan on having them there. We're currently discussing HW budget for additional clusters and I'm sure we will have GPUs on future clusters.

Is GPU a hard requirement for you, right now? @pacospace 

/kind question
/sig user-experience

**Comment by pacospace** [comment]
> We don't have GPUs in the zero cluster neither we plan on having them there. We're currently discussing HW budget for additional clusters and I'm sure we will have GPUs on future clusters.
> 
> Is GPU a hard requirement for you, right now? @pacospace
> 
> /kind question
> /sig user-experience

Not a very hard requirement, but it might be nice to have soonish for some use cases.

cc @harshad16 for tf-gpu-buil and tensorRT

**Comment by durandom** [comment]
nope, unfortunately not.
@billburnseh @msdisme ?

**Comment by billburnseh** [comment]
I do not have an ETA for arrival or availability, defer to Michael.

**Comment by pacospace** [comment]
Any update on this issue?

**Comment by durandom** [comment]
@msdisme @accorvin  any updates on the GPUs that have been shipped to the BU datacenter?
@accorvin can you post the number and type of the GPUs here real quick?

**Comment by msdisme** [comment]
I believe they have arrived – not sure of the quantity but I will look at getting them installed in the next week or so – more specific details as soon as I have them.

Also, we are working to put in place a relationship with a group that has people  onsite at the data center so that we have more flexibility – I do not have an eta on that yet.

From: Marcel Hild ***@***.***>
Date: Monday, September 6, 2021 at 9:36 AM
To: operate-first/support ***@***.***>
Cc: Daitzman, Michael S ***@***.***>, Mention ***@***.***>
Subject: Re: [operate-first/support] GPU Supported in Operate First (#147)

@msdisme<https://github.com/msdisme> @accorvin<https://github.com/accorvin> any updates on the GPUs that have been shipped to the BU datacenter?
@accorvin<https://github.com/accorvin> can you post the number and type of the GPUs here real quick?

**Comment by msdisme** [comment]
Crosslinking this ticket with https://github.com/CCI-MOC/ops-issues/issues/312

**Comment by accorvin** [comment]
@durandom they should have received 3 P100s

**Comment by msdisme** [comment]
we plan to put those into individual machines for now.  We will keep our eyes out for systems capable of handling multiple GPU's.

**Comment by MichaelClifford** [comment]
@msdisme any update on this? Are the GPU's available?

**Comment by durandom** [comment]
@msdisme @larsks are those cards by any chance in any of the smaug nodes?
