### ISSUE TITLE
Manage APIs with 3Scale

### ISSUE THREAD

**Issue by fridex** [operate-first/support#171]
### Requested actions

Deploy 3Scale API (or similar project) for managing APIs.

#### Operator request

If you want to request an operator, please provide the following:

1. **Name of the Operator**:

3scale operator

2. **Operator version**:

No requirement on a specific version.

3. **Operator scope**:

For us, it is OK to work just on Thoth's frontend namespace.

4. **Documentation and links**:

https://access.redhat.com/documentation/en-us/red_hat_3scale_api_management/2.9/

### Questionnaire

1. **Team name**:

Thoth

**Comment by tumido** [comment]
Thank you @fridex for this ticket. At first we will have to resolve 2 limitations on 3Scale side:

- OpenShift 4.7 is still [unsupported](https://access.redhat.com/articles/2798521)
- Requires additional RH subscription entitlement on the nodes
   1. I have no idea how that scales (with dynamically provisioned/reprovisioned nodes) since the  docs mention a manual entitlement on every machine in the cluster
   2. No idea if BU account has an entitlement available for it

We'll look into it probably in the upcoming sprint.

**Comment by fridex** [comment]
As I don't know 3scale, I'll post also our requirements for API management to see if 3scale fits or if we need to find any other product that would serve our purposes well:

* throttle requests from the same IP address - not to allow users post/get requests in a loop making the service not available/high on load
  * this can be also accomplished using a token (e.g. as github throttles unauthenticated requests)
  * as the service is exposed to the internet, any DoS/DDoS prevention is a plus

* allow having some endpoints unauthenticated
  * some can require an optionally supplied token
  * if a token can be only turned on/off for certain endpoints, we can restructure our endpoints slightly to have some token guarded and some token-free

* ... (will add if something comes to our minds)
