### ISSUE TITLE
Is OpenShift's registry available to push images to?

### ISSUE THREAD

**Issue by rob-baron** [operate-first/support#178]
If not, can it be made available?

If yes, what is the address to push images to it?

**Comment by tumido** [comment]
I don't we want users to be pushing to the internal image registry directly. You can import images via `ImageStream`s or reference them remotely and kubernetes will pull them in. We advise to use quay.io for hosting your images.

Or do you want us to maintain a private image registry via Registry Operator?
https://docs.openshift.com/container-platform/4.7/registry/configuring-registry-operator.html

Thought @larsks @HumairAK @durandom

**Comment by larsks** [comment]
@tumido what's the objection to having user''s push directly to the internal image registry?

**Comment by tumido** [comment]
@larsks Maybe I put it wrong, sorry :smile: ... My objections was that the internal registry is not accessible directly per-se in OCP4. Only via Registry Operator:

https://docs.openshift.com/container-platform/4.7/registry/securing-exposing-registry.html

And since this configuration is not automated for baremetal installs, we would need to configure it manually. 
https://docs.openshift.com/container-platform/4.7/registry/configuring-registry-operator.html#image-registry-on-bare-metal-vsphere

```
oc get configs.imageregistry.operator.openshift.io cluster -o jsonpath='{.spec.storage.managementState }'
Unmanaged
```

IMO for rapid development I think it's easier to run the container for example locally and use SA credentials to provide it access to the cluster. Also Eclipse Che might be a good RFE for us for cloud native development... Now I'm diverting too much from the topic though.

**Comment by HumairAK** [comment]
@tumido that's interesting, so I had a skim over the links you provided. The way I understand it, the suggestion to expose the internal registry via a route requires us to update the `configs.imageregistry.operator.openshift.io` resource, but because `managementState` is set to `Unmanaged` -- these changes would not be picked up. Is that right? 

If so -- what would it take for us to have it set to `Managed`?

**Comment by tumido** [comment]
@HumairAK no idea, :shrug:

The docs don't mention `Unmanaged` state to naturally occur on bare metal install. It talks about `Removed` state all the time and changing it to `Managed`.

I'm unsure, it would need further investigation into this topic. In the worst case we would need to manage it manually... I also don't think we want to experiment with image registry on a live system without proper knowledge potentially breaking the image registry for all the users...
