### ISSUE TITLE
I want to be able to use OperateFirst for cloud native development via Eclipse Che (CodeReady Workspaces)

### ISSUE THREAD

**Issue by tumido** [operate-first/support#182]
#### Operator request

If you want to request an operator, please provide the following:

1. **Name of the Operator**: RedHat CodeReady Workspaces

2. **Operator version**: 2.7

3. **Operator scope**: Single namespace `openshift-workspaces`, later on, the project strategies are configurable (see https://access.redhat.com/documentation/en-us/red_hat_codeready_workspaces/2.7/html/installation_guide/configuring-che_crw#configuring-namespace-strategies_crw)

4. **Documentation and links**:
   https://access.redhat.com/documentation/en-us/red_hat_codeready_workspaces/2.7/html/installation_guide/index
   https://developers.redhat.com/products/codeready-workspaces/overview
   https://www.eclipse.org/che/docs/che-7/installation-guide/installing-che-on-openshift-4-using-operatorhub/
   https://operatorhub.io/operator/eclipse-che

### Questionnaire

1. **Team name**: operate-first

**Comment by HumairAK** [comment]
I talked with @JPinkney and he directed me to https://marketplace.visualstudio.com/items?itemName=redhat.vscode-didact 

This is really cool stuff, very katacoda like experience (but with a full fledged ide) that we can offer within our docs. @durandom you probably want to take a look at this as well.

**Comment by HumairAK** [comment]
Messed around with this yesterday on quicklab instance. So it seems llke che (or the operator? not sure) will create new namespaces for each user. So kind of like kubeflow. Not sure if this is a deal breaker or not, I still find the tooling _very_ interesting and would like to see if we can work around it somehow, looking for thoughts from others @tumido @4n4nd

**Comment by tumido** [comment]
/kind onboarding
/priority imporant-longterm

I think we still want this. I also agree with you, that might be an issue in case of name conflicts and it can have possible security implications (like if I create GitHub account with the same name as any of the existing namespace, can I effectively hijack a namespace?). Maybe a dedicated dev cluster is the way to go....

**Comment by tumido** [comment]
Is there a way to limit the number of namespaces? I thought each user gets a new/own one, right?

**Comment by tumido** [comment]
ok.. do we have any way to limit the amount of users other than not telling folks the url? :smile: 

I'm all for this, I just want no surprises :slightly_smiling_face:

**Comment by HumairAK** [comment]
I'll have to investigate, but I'm sure there's restrictions we can add either via access control or some other config -- 

So I'm taking that as: as long as we can hard limit the number of namespaces via some configuration mechanism, let's try this out on smaug with some hard cap of at most 5-10 user namespaces.

**Comment by 4n4nd** [comment]
let's get the ops people (us) start using this instead of our local envs and see if we like it and it would be good idea

**Comment by HumairAK** [comment]
Okay so a few things after playing with it a bit more: 

1) I can disable auto namespace creation, so that a user will need to request a namespace via a PR before proceeding to create any workspaces 

2) Che requires an identity provider, by default it provisions it's own keycloak to do this, which also deploys an openshift Oauth client, and delegates auth via the hosting openshift instance. I thought about just using our keycloak to do authentication instead, but it seems to require access to the external keycloak's postgresql credentials...which seems strange to me. It also doesn't give any way to pass the client secret to che :shrug: 

It also has this `nativeUserMode` : 
> Enables native user mode. Currently works only on OpenShift and DevWorkspace engine. Native User mode uses OpenShift OAuth directly as identity provider, without Keycloak. 

Which seems better to me, since the openshift auth is redirected to our main keycloak instance, it gets the intended result. 
Anyone gets access, but only those with a namespace can create a workspace. Sounds good enough to me.

**Comment by tumido** [comment]
I like the `nativeUserMode` :+1:
