### ISSUE TITLE
Setup credentials in Hue to access private bucket

### ISSUE THREAD

**Issue by xtuchyna** [operate-first/support#183]
**Description**
Hello, I would like to access private bucket within Hue, so that I can connect to it and create tables out of data that is stored on that bucket.

Where can I find instructions to do that? Seems like currently this cannot be set within the UI, maybe there's some issue?

**Additional context**
The `Actions` option is grayed out and cannot be used
![image](https://user-images.githubusercontent.com/46632404/113181486-22938980-9252-11eb-8908-c5a50c5c6d0e.png)

**Comment by tumido** [comment]
That is currently not possible. Hue allows to use only a single set of S3 credentials per user group. Since we don't have SSO enabled yet on Hue, there's no more than a single user available

https://docs.cloudera.com/documentation/enterprise/5-14-x/topics/hue_use_s3_enable.html

If you don't need the S3 file browser in Hue and once #131 is resolved, you can use whatever credentials you want for the Hive tables since Hive is independent from Hue.
