### ISSUE TITLE
Deployment of a helm chart on operate first

### ISSUE THREAD

**Issue by tloubrieu-jpl** [operate-first/support#206]
**Description**
I am trying to deploy a helm chart on operate first, project sdap.

I opened a terminal and run the following commands:
```
$ git clone https://github.com/apache/incubator-sdap-nexus.git
$ helm install nexus incubator-sdap-nexus/helm --namespace=sdap --dependency-update

```
And I am getting the following error:
```
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /home/user/.kube/config
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /home/user/.kube/config
Getting updates for unmanaged Helm repositories...
...Successfully got an update from the "https://charts.helm.sh/incubator" chart repository
Killed
```

It work in our local environment.

Thanks for your help.

**Comment by tumido** [comment]
Hi @tloubrieu-jpl it seems to me this error is actually on your end. Let's check if you can render those templates first. Can you please try running:

```
helm template  incubator-sdap-nexus/helm
```

Can you get the output?

Additional to that I can see that the chart you're trying to apply include custom resource definitions and cluster roles and using operators which are not deployed on the cluster. If you want to apply those resources, you would need to add them into our `cluster-scope` application, since the presence of these resources effect all the tenants on the cluster.

Kinds that can't be deployed by regular users in your chart are:
- `CustomResourceDefinition`
- `ClusterRoleBinding`
 
You will also need to deploy the spark operator and the `CustomResourceDefinition` for your `SparkApplication` manifest, since this operator is not present on the cluster.

**Comment by tloubrieu-jpl** [comment]
Hi @tumido, thanks for you feedback.

The output of command

```
$ helm template  incubator-sdap-nexus/helm
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /home/user/.kube/config
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /home/user/.kube/config
Error: found in Chart.yaml, but missing in charts/ directory: nginx-ingress, rabbitmq, solr, cassandra

```

I think the error is supposed to be solved by the option ` --dependency-update` that I have in the helm install command, that is apparently what causes the error, like if i do:

```

bash-4.4 ~ $ helm template  incubator-sdap-nexus/helm --dependency-update 
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /home/user/.kube/config
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /home/user/.kube/config
Getting updates for unmanaged Helm repositories...
...Successfully got an update from the "https://charts.helm.sh/incubator" chart repository
Killed

```

That is how we usually deploy this chart. Can you give more details on how to add resources in the `cluster-scope` since I never did that manually.

Thanks for your support,

**Comment by tumido** [comment]
Hm, that is very weird, since I can't replicate that locally. From fresh clone, you're right though, the `--dependency-update` flag is required. Other than that I can render it just fine...

```
$ cd /tmp/x                   

$ git clone https://github.com/apache/incubator-sdap-nexus.git
Cloning into 'incubator-sdap-nexus'...
remote: Enumerating objects: 213, done.
remote: Counting objects: 100% (213/213), done.
remote: Compressing objects: 100% (190/190), done.
remote: Total 3379 (delta 79), reused 61 (delta 23), pack-reused 3166
Receiving objects: 100% (3379/3379), 4.78 MiB | 6.46 MiB/s, done.
Resolving deltas: 100% (1777/1777), done.

$ helm template incubator-sdap-nexus/helm                     
Error: found in Chart.yaml, but missing in charts/ directory: nginx-ingress, rabbitmq, solr, cassandra

$ helm template incubator-sdap-nexus/helm --dependency-update
Getting updates for unmanaged Helm repositories...
...Successfully got an update from the "https://charts.helm.sh/incubator" chart repository
...Successfully got an update from the "https://charts.bitnami.com/bitnami" chart repository
...Successfully got an update from the "https://charts.bitnami.com/bitnami" chart repository
...Successfully got an update from the "https://charts.helm.sh/stable" chart repository
Hang tight while we grab the latest from your chart repositories...
Update Complete. ⎈Happy Helming!⎈
Saving 4 charts
Downloading nginx-ingress from repo https://charts.helm.sh/stable
Downloading rabbitmq from repo https://charts.bitnami.com/bitnami
Downloading solr from repo https://charts.helm.sh/incubator
Downloading cassandra from repo https://charts.bitnami.com/bitnami
Deleting outdated charts
---
# Source: nexus/charts/cassandra/templates/pdb.yaml
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: RELEASE-NAME-cassandra-headless
  labels:
    app: cassandra
    chart: cassandra-5.5.3
    release: RELEASE-NAME
    heritage: Helm
...
```

`helm template` should be a completely offline command. Even if I remove my `~/.kube` folder, I can run it just fine even against a fresh clone. Can you try this against a fresh repo clone as well?

Can you please also share what version of Helm you're using (`helm version`)?

**Comment by tloubrieu-jpl** [comment]
I did the test this morning from a fresh repo since I don't have a persistent volume where to clone my repository. When I restart a terminal I am starting in /home/users which is empty.

I also have warnings that you don't have:
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /home/user/.kube/config

Could that be related to the fact that I don't have a persistent home directory ? 

The helm version is :
version.BuildInfo{Version:"v3.5.0+6.el8", GitCommit:"77fb4bd2415712e8bfebe943389c404893ad53ce", GitTreeState:"clean", GoVersion:"go1.14.12"}

**Comment by HumairAK** [comment]
> I did the test this morning from a fresh repo since I don't have a persistent volume where to clone my repository 

Hrmm a bit confused, can you explain what environment are you running this command? Is it a container? pod?

**Comment by HumairAK** [comment]
Possibly related: https://github.com/helm/helm/issues/8776#issuecomment-742607909 ?

**Comment by tloubrieu-jpl** [comment]
I am running the command from a terminal that I opened from the console ('>_' in the upper right menu).

When I click this option, it starts a pod actually and I am running the command from with the pod I guess... Is there a way to get a terminal window on the host ? Sorry obviously I am new to this environment ;)

**Comment by HumairAK** [comment]
Ahh I understand now. I'm not really sure about using helm via the OCP CLI. But you can run the helm commands on your local machine. I'm not sure _exactly_ how `helm install` works, but you could also do something like

```
# Pre-condition: have helm installed on your local machine
~ $ git clone https://github.com/apache/incubator-sdap-nexus.git
~ $ cd incubator-sdap-nexus
~ $ helm template  incubator-sdap-nexus/helm --dependency-update | oc apply -n <your-namespace> -f - 
```

Anyways this should render just fine, but the `oc apply` will fail because as @tumido said there are some cluster resources included in this helm chart, and we do not allow users to directly deploy these (due to security concerns). 

However you can add these cluster resources to our repo and then they will be auto deployed on the cluster. They all go in this location [here](https://github.com/operate-first/apps/tree/master/cluster-scope). There is a readme there that explains the structure. But in general you would add: 

- add the `clusterrolebindings` in the `cluster-scope/base/clusterrolebindings` folder 
- add the `clusterroles` in the `clusterroles` folder 
- ...repeat for other resources

Then you add these to the kustomization file as done so for the other cluster manifests [here](https://github.com/operate-first/apps/blob/master/cluster-scope/overlays/moc/zero/kustomization.yaml). This will declaratively add these resources to the "Zero" ocp cluster.

Then create a PR.

For deploying via the helm chart, I would suggest having a variable that disables all cluster resources from rendering, then use this to render only non-cluster resource files.

**Comment by tloubrieu-jpl** [comment]
Hello @HumairAK , @tumido ,

Sorry I had to pause to work on something else.

I am now able to deploy on the operate first cluster simply by login `oc login` and then using commands `kubectl ...` or `helm ...` locally.

I've just created a pull request to update the resource I am not able to create directly, see https://github.com/operate-first/apps/pull/642

Let me know if I need to correct something (I am expecting that since I am not really sure what I am actually doing ;))

Thanks very much.

**Comment by tumido** [comment]
Hey @tloubrieu-jpl ! thank you for submitting a PR! We're always very pleasantly surprised when we have new contributors! I love it. :slightly_smiling_face:  I think that we have some security concerns about the Google Spark operator deployed this way, however that should not stop us. I've found few people who should be able to help us with it and we should bring that on in a proper, supportable way. So I suggest to bring SDAP CRDs and RBAC separately and coordinate the Google Spark operator here: https://github.com/operate-first/support/issues/241
