### ISSUE TITLE
Cluster onboarding for the Sigstore team

### ISSUE THREAD

**Issue by mbestavros** [operate-first/support#245]
## Questionnaire

1. **Project description**:

   

   PROJECT DESCRIPTION:

From the [website](https://sigstore.dev/what_is_sigstore/): "`sigstore` is a project with the goal of providing a public good / non-profit service to improve the open source software supply chain by easing the adoption of cryptographic software signing, backed by transparency log technologies."

2. **Target cluster**:

    

    TARGET CLUSTER: `Zero`

3. **Team name**:

    

    TEAM NAME: sigstore

4. **Desired project names**:

    

    PROJECT NAMES: sigstore

5. **Users needing access**:

    

    LIST OF USERS: (would prefer to keep email addresses private)

6. ** Namespace Quota **

    

    QUOTA: Small

7. **GPG Key** (OPTIONAL)

    

    GPG KEY FINGERPRINT:
    KEYSERVER:

---

This is my first exposure to the MOC, so some of this may be subject to change -- but these are the basics for now :)

**Comment by HumairAK** [comment]
@mbestavros in general we encourage users to have a suffix after their namespace, so that if the team requests more namespaces they can continue to use their team name prefix. Something like: 
`sigstore-<suffix-1>` 
`sigstore-<suffix-2>` 

Do you have a preference for a suffix here for this namespace?

**Comment by mbestavros** [comment]
@HumairAK Maybe `sigstore-deploy`?
