### ISSUE TITLE
Support a 3scale's Authorino

### ISSUE THREAD

**Issue by paoloantinori** [operate-first/support#253]
**Is your feature request related to a problem? Please describe.**
It would be useful to have a reverse proxy solution to protect endpoints.
3scale has created an interesting new project that is a logical and cloud native evolution of Keycloak Gatekeeper and Keycloak Lokueto. https://github.com/Kuadrant/authorino
Being based on a CRD + Operator pattern should ideally fit well with Operate First infrastructure services offering.

**Describe the solution you'd like**
As a user of the platform, I'd like to be able to get some kind of authZ/authN for my services just defining specific CRDs.

**Describe alternatives you've considered**
To address our specific request, Authorino is considering support for a user level config that won't required an Operator to be installed on the cluster.

**Comment by paoloantinori** [comment]
It could also fit in this larger story: https://github.com/operate-first/support/issues/248

**Comment by durandom** [comment]
cc @fridex @goern not sure if thoth has similar requirements.

@paoloantinori also deployed https://github.com/3scale-labs/limitador in his namespace, maybe that's interesting too

**Comment by tumido** [comment]
The deployment docs are not that precise.

https://github.com/Kuadrant/authorino/blob/master/docs/deploy.md#option-b-custom-deployment 
They mean to deploy the project against a live cluster directly via `make deploy` - whoever attempts to implement this issue be aware and don't run the command unless you know which cluster your `kubectl` is pointing at.

We may want to prefer their OpenShift demo way of deploying things:
https://github.com/Kuadrant/authorino/tree/master/docs/tutorials/openshift-demo

That should give us better manifests directly. I think we can take a look into this in the next maybe. It's a good onboarding excercise.

**Comment by paoloantinori** [comment]
we can try asking directly @guicassolato if you need any detail!

**Comment by guicassolato** [comment]
Absolutely, @paoloantinori and @tumido! I'll be glad to help.
In fact, it will also be an opportunity to improve our docs.

**Comment by tumido** [comment]
Awesome! :slightly_smiling_face: I'm sorry, my comment may have came across a bit rude, I didn't mean to - I just took a quick glimpse at your docs to assess the task before we plan on deploying it and just quickly wrote down my findings in here as a sort of "note to self" type of comment. :slightly_smiling_face: 

> In fact, it will also be an opportunity to improve our docs.

Oh, and we'd be definitely interested in helping you with that! :slightly_smiling_face: I think we already have a pretty good idea of how an ideal deployment experience for a cloud operator looks like - and we should be able to share that and either contribute to your docs or even help with structuring your manifests. :+1:

**Comment by guicassolato** [comment]
No offense taken, @tumido. No worries 🙂

Our docs are indeed in a weird state right now, where most of our examples were thought and tested in a deployment based on a local cluster spawned with kind, and then we have that [Option B: Custom deployment](https://github.com/Kuadrant/authorino/blob/master/docs/deploy.md#option-b-custom-deployment) that you mentioned, which basically translates to "Hey, these are the bits and pieces, but since we don't know the exact context, you're more or less on your own." (The latter is something we want to improve of course.)

About using https://github.com/Kuadrant/authorino/tree/master/docs/tutorials/openshift-demo, I'd be careful too. The example points to a gist that will work perfectly fine as long as you use the Authorino container image also pointed in the example. For `quay.io/3scale/authorino:latest`, we need updated CRD spec, e.g.

We'll probably need to work together to come to the exact yaml files and deployment recipe that will best work for Operate-First, perhaps starting with this minimal piece:

```
kustomize build config/crd
```

Then there's RBAC stuff (leader election, custom controller permissions and metrics endpoint), and finally the Authorino manager itself. I can try working a little bit on the kustomize files and make targets to ease the process.

I think will probably want Authorino controllers confined within the user space - i.e. watching only the CRs and Secrets created in the same namespace. Is that right? If so, there's a pending change in https://github.com/Kuadrant/authorino/pull/99 that will make this possible. On the other hand, if the idea for Operate-First is to have only one instance of Authorino for the entire cluster (watching CRs created in all namespaces), then we might need to add some extra protection for users of one namespace not to start messing with the protection of APIs running on another namespace.
