### ISSUE TITLE
`oc get all` throws "Forbidden" errors in the sigstore-deploy project

### ISSUE THREAD

**Issue by mbestavros** [operate-first/support#255]
**Describe the bug**
In experimenting around with the `sigstore-deploy` project, me and a few others tried running `oc get all` and got what appears to be permissions errors:

```shell
Error from server (Forbidden): virtualmachineimports.v2v.kubevirt.io is forbidden: User "<email address>" cannot list resource "virtualmachineimports" in API group "v2v.kubevirt.io" in the namespace "sigstore-deploy"
Error from server (Forbidden): vmimportconfigs.v2v.kubevirt.io is forbidden: User "<email address>" cannot list resource "vmimportconfigs" in API group "v2v.kubevirt.io" at the cluster scope
Error from server (Forbidden): resourcemappings.v2v.kubevirt.io is forbidden: User "<email address>" cannot list resource "resourcemappings" in API group "v2v.kubevirt.io" in the namespace "sigstore-deploy"
Error from server (Forbidden): applications.app.k8s.io is forbidden: User "<email address>" cannot list resource "applications" in API group "app.k8s.io" in the namespace "sigstore-deploy"
```

@larsks suggested I open this issue to investigate whether this is something that should be fixed.

**To Reproduce**
1. Open a shell as admin of the `sigstore-deploy` project
2. Run `oc get all`
3. Encounter `Forbidden` errors

**Expected behaviour**
`oc get all` should return results without errors.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by larsks** [comment]
@mbestavros I have some questions about this issue. Is this just an informational question, or are these errors preventing you from doing something? In what context are you running `oc get all`? Generally that command is only mildly useful, since it doesn't actually list *all* resources.

It looks like most of the errors are from kubevirt-related resources, so we're going to try to follow up with that team to see if there's a particular reason the RBAC on these resources doesn't allow list access from a project admin.
