### ISSUE TITLE
Cluster basis configuration not fully documented in Git. 

### ISSUE THREAD

**Issue by rbo** [operate-first/support#307]
**Description**

If I'm looking into [ArgoCD](https://argocd.operate-first.cloud/applications?proj=cluster-management&sync=&health=&namespace=&cluster=&labels=&view=list) I recognize that the infra cluster have more than one application. But there is it document which cluster gets which applications? 

![image](https://user-images.githubusercontent.com/36604/125628293-1baaeffb-6f08-4a92-a0d9-f4bb59e3c303.png)

One example: infra cluster is configured to forward all Prometheus alerts to a local alert receiver, but the local alert receiver is deployed via its own application. So someone has to know that [basic cluster configuration](https://github.com/operate-first/apps/tree/master/cluster-scope/overlays/prod/moc/infra) need a local alert receiver too. 

Why is the local alert receiver not part of one basic cluster configuration? 

Another question in that corner: Do you consider using RHACM to rollout basic cluster configuration and not ArgoCD? 

**Additional context**

 * https://operatefirst.slack.com/archives/C01RT0S2WKX/p1625841302497000 details sadly not in a single thread :-(

**Comment by rbo** [comment]
Here an example: https://github.com/stormshift/clusters/tree/first-try

**Comment by HumairAK** [comment]
/cc @larsks @4n4nd 
Figured you might have some opinions here :) 

>  But there is it document which cluster gets which applications?
>  Why is the local alert receiver not part of one basic cluster configuration?

So we discussed this in slack earlier, but to paint the context -- I think what @rbo is trying to get at is, if you are setting up a new cluster, and want to just create an Argocd App that will deploy all the basic cluster configurations, then why is the alert receiver not included in the `cluster-resources` app?

I think - that our set up is designed so that the `cluster-resources` app isn't really for "basic configurations". It is for privileged resources that users cannot deploy themselves (CRDs, CRs, subscriptions, etc.). You can pick and choose _which_ of these resources you want in your cluster, by referencing them in cluster overlays. 

Everything that falls outside of the realm of "privileged resource" i.e., things that anyone can deploy (much like how we expect our users to), goes in to a separate app _not_ in `cluster-resources`. One reason why we do this is so that we can deploy such apps in separate namespaces/environments, so that they are not restricted to only serve cluster-management purposes. For example, if we want to deploy the github alert receiver in a separate namespace, and configure it to receive alerts from a different prometheus (not the one from openshift monitoring), then it is not really a "cluster management" app, if that makes sense.

I don't think we have any logical grouping/docs on how to deploy a _basic configuration_ (how do you define basic configuration btw?), the closest thing we have is the grouping of all these apps (relevant to cluster management) belonging to the `cluster-management` argocd project. We could certainly curate this project further so it can serve this purpose. Not sure if that would solve the problem. But you can deploy a project, and a set of applications within that project with a few small clicks/commands if properly configured.

> Do you consider using RHACM to rollout basic cluster configuration and not ArgoCD?

I'm not super familiar with RHACM, but I think some other folks have played around with it and found it a bit lacking compared to ArgoCD. Is there any particular reason you would prefer RHACM over ArgoCD?

**Comment by rbo** [comment]
> I'm not super familiar with RHACM, but I think some other folks have played around with it and found it a bit lacking compared to ArgoCD. Is there any particular reason you would prefer RHACM over ArgoCD?

I don't know, this is what I like to figure out. Maybe together with operate first. Because this is a typical customer question.

**Comment by rbo** [comment]
Now I understand it better, right now it is document: https://github.com/operate-first/apps/blob/master/argocd/overlays/moc-infra/applications/envs/emea/morty/cluster-management/kubevirt-hyperconverged.yaml - app-of-apps gitops approach. For me we can close the issue.
