### ISSUE TITLE
Feasibility for AIOps on alerts/issues data

### ISSUE THREAD

**Issue by davidohana** [operate-first/support#312]
Hi @tumido 

I work with Eran and Bruno on the AIOps effort.  Eran suggested that the data you have is pretty similar to another use case in which we have successfully applied a supervised model for alert filtering, prioritization, and localization.
We would like to create a supervised model which will "predict" whether an alert candidate in https://github.com/operate-first/alerts is relevant and as such will be able to promote it to get better attention from the SREs. It may also group alerts of the same component together in a hierarchical structure, to provide system-level and sub-system anomaly scores and alerts.
 
I have few questions regarding the data, before trying to apply our approach to it:

1.  Are alerts in https://github.com/operate-first/alerts automatically opened by a tool?  Do you also manually create alerts in some cases?

For supervised learning, we need labels on whether an alert is interesting/relevant. One option for determining if an alert is useful is to check whether there was human interaction with the alert - acknowledging it, assigning, commenting, resolving, etc ..

2. Are the alerts ever touched by humans? what is a typical flow of handling an alert? Or can you suggest another approach for determining if an alert is relevant?

Another option for determining if an alert is useful is performing an indirect correlation between alerts and incident tickets. For this, we may use https://github.com/operate-first/SRE/issues and perform a temporal+spatial correlation between alerts and tickets. Spatial correlation is not mandatory but it may help a lot to improve accuracy and avoid noise.

3. Is there a way to determine whether an issue is an incident or a Change Request?
4. Is there a way to determine whether an issue was opened based on an alert? Do you reference the original alert somehow?
5. Is there a way to extract from an issue what was the affected component(s)? We 
 
Note: The information I ask for in 3-5 might not be structured, we can also try some heuristics to extract it.

Thanks
David

**Comment by eranra** [comment]
@durandom FYI ^^^

**Comment by 4n4nd** [comment]
> Are alerts in https://github.com/operate-first/alerts automatically opened by a tool? Do you also manually create alerts in some cases?

In that repo, the alerts are prometheus alerts. We get openshift cluster alerts, but since there were a few alerts that were too frequent and created a lot of noise, we tried to silence them (configured [here](https://github.com/operate-first/apps/blob/master/cluster-scope/overlays/prod/moc/common/alertmanager-main-secret.yaml)) and also some user side application alerts that are configured [here](https://github.com/operate-first/apps/blob/master/odh-manifests/prometheus/operator/overlays/alerts/prometheus-rules.yaml).

> Are the alerts ever touched by humans? what is a typical flow of handling an alert? Or can you suggest another approach for determining if an alert is relevant?

Currently we don't have a fixed workflow on how these alerts are handled, but we do have a bunch of issues created for this ([here](https://github.com/orgs/operate-first/projects/26)) where we are discussing on how to manage these alerts and how ops engineers will be assigned to these alerts (specifically this [issue](https://github.com/operate-first/SRE/issues/349) might be of your interest).

> Is there a way to determine whether an issue is an incident or a Change Request?

Usually an ops engineer will look at the alerts and create a corresponding Incident issue in the SRE repo ([example](https://github.com/operate-first/SRE/issues/351)).

> Is there a way to determine whether an issue was opened based on an alert? Do you reference the original alert somehow?

All the issues in the alerts repo are alerts created based on some prometheus alerting rules. We reference the alert issues in the incident issues that the ops engineers create. Ideally we would want to use the original alert issue that was created in the alerts repo but since there is a lot of noise in that repo, we create new issues in other relevant repos.

>Is there a way to extract from an issue what was the affected component(s)? 

the created alerts usually contain the namespace and service of the component that has broken ([example](https://github.com/operate-first/alerts/issues/11832)), we are also planning to forward these prometheus labels as github issue labels.

@HumairAK and @tumido please correct me if I am wrong

**Comment by durandom** [comment]
@davidohana is the answer by @4n4nd sufficient?

Like discussed with @eranra it would be great to get a model trained on the data that is currently available, even if it's not super useful - because we dont have *enough* data. Eventually there will be enough data, we should make sure now, that the data has the right structure and qualities, features.

So, a notebook for model training would be super awesome. And if the notebook would be developed on ODH in this environment, even better.
We can then take it and create a pipeline and deploy the model as a service and iterate on it.

Have a look at https://github.com/AICoE/elyra-aidevsecops-tutorial - this tutorial has all the moving parts for creating Kubeflow pipelines and might serve as a starting point.

**Comment by davidohana** [comment]
@durandom @4n4nd Sorry for the late response, forgot to write the reply.
I think that currently, the data is not in a usable shape for applying ML, and we may need to enhance the workflow for processing alerts and make it more structured so that we can create a model of it in few months.
The most important thing is a way to determine if an alert is "interesting" or "relevant", so that we have labels for supervised learning. 
It can be either:

1. A direct "ack" or a comment to an interesting alert.
2. A structured back-reference from an issue to the triggering alert.
3. An indirect correlation by timestamp + component. For this, we need to specify in each issue what was the outage start date/time and the affected component, and also have the same notion of affected components in the alert itself so we may be able to correlate. 

From a quick look I made so far, indeed in some alerts/issues we have this info but the data and structure in the alerts and issues repos is not consistent, and we cannot extract and use it reliably enough.

So I think, if you are interested, we first need to agree on a workflow and a schema for alert processing.

**Comment by hkkolodner** [comment]
@hkolodner so I will get updates

**Comment by durandom** [comment]
@4n4nd can you link to the operational procedure, i.e. probably something like https://www.operate-first.cloud/operations/sre/incident-management/incident-management-procedure.md , which defines the workflow for alert processing?

**Comment by durandom** [comment]
@davidohana if you're still interested in working with our data, please re-open this issue

/close
