### ISSUE TITLE
Setup proper (letsencrypt?) certificates for ingress.

### ISSUE THREAD

**Issue by rbo** [operate-first/support#339]
Setup proper certificates for ingress.

**Comment by HumairAK** [comment]
I believe we use Openshift ACME for this for zero cluster, see [here](https://github.com/operate-first/apps/blob/63e2edab970133f7b0ab4826a870ab80e0867efb/docs/issuing_certificates.md#securing-openshift-routes-with-acme-lets-encrypt). @tumido set this up. WDYT?

**Comment by tumido** [comment]
ACME controller is not capable of this, since ingress needs a certificate secret, while ACME operator can work with routes only.

I even think @larsks had a support case opened on this a while back to provide us guidance on automation of this - without a result. For now we manage those certs manually. Here's an example for zero:
https://github.com/operate-first/apps/blob/master/cluster-scope/overlays/prod/moc/zero/ingresscontrollers/default-ingress-certificate.enc.yaml

**Comment by larsks** [comment]
@HumairAK @tumido I think we can close this now, yes?

**Comment by HumairAK** [comment]
Yeah we have a framework in place on how to do this for other clusters. If this issue was about a specific cluster let's get another one going on bringing certs to it via cert manager using our current workflow.

**Comment by rbo** [comment]
Just for documentation: part of  https://github.com/operate-first/apps/issues/1471
