### ISSUE TITLE
Desktop App + GUI for OCTO Summit Demo

### ISSUE THREAD

**Issue by TreeinRandomForest** [operate-first/support#481]
**Is your feature request related to a problem? Please describe.**

For the OCTO summit demo, we need to train a model for a self-driving car on the operate-first cluster. This requires running a desktop application: [Simulator](https://github.com/tawnkramer/gym-donkeycar/releases/download/v21.07.24/DonkeySimLinux.zip) that pops up a GUI on the desktop. Is it possibly to run this binary in a containerized environment (for e.g. from the shell in Jupyter) and still have access to the GUI?

**Describe the solution you'd like**
Ideally, a user could just run the application from the terminal in a Jupyter notebook. A data scientist would need this app to run to test/train self-driving cars in a simulator.

**Describe alternatives you've considered**
(1) try a headless build of the application using the Unity game engine (where the simulator was developed). This would ideally let one run a background process that python code could interact with. (2) Do all the simulator work outside the cluster i.e. locally on a desktop.

**Additional context**
The application is a car simulator written in the Unity game engine. It is needed to (1) drive a car and collect data that can be used to train a model, (2) use a model to drive a car in the simulator to evaluate model performance.

@MichaelClifford @sub-mod

**Comment by HumairAK** [comment]
Disclaimer: I don't know anything about running unity builds in k8s/containerized environments

This sounds more like a general question about running unity builds in a containerized k8s environment, rather than operate-first specific. 

> Is it possibly to run this binary in a containerized environment (for e.g. from the shell in Jupyter) and still have access to the GUI?

It can run in a containerized environment sure, but you can't access the gui as it would be running on a separate machine..

The general pattern to access application gui's is through the browser. I suppose in unity's case this would be something like webgl/opengl.

**Comment by TreeinRandomForest** [comment]
Ok. Technically, it is possible to ssh into a container and use X11 forwarding to run a GUI based app but forward the display to the host from the server. I would guess this is not encouraged in k8s. We will try the headless build and if that fails, do the simulator-based work locally.
