### ISSUE TITLE
Ceph/S3 should allow to enforce bucket policies and should be able to be exposed externally

### ISSUE THREAD

**Issue by tumido** [operate-first/support#53]
**Is your feature request related to a problem? Please describe.**
Ceph/S3 should allow to enforce bucket policies and should be able to be exposed externally. For some applications we need to produce buckets with a single user access - separate set of credentials with 

**Describe the solution you'd like**
- User specific policies per bucket
- External route to ceph

**Describe alternatives you've considered**
ma

**Additional context**
- https://gitlab.com/open-infrastructure-labs/moc-cnv-sandbox/-/issues/33
- https://github.com/operate-first/support/pull/49#issuecomment-765619619
- https://github.com/operate-first/support/issues/31
- https://github.com/noobaa/noobaa-operator/blob/master/doc/obc-provisioner.md
- https://github.com/noobaa/noobaa-core/wiki/Bucket-Website-Support
- Rook proposal (NOT IMPLEMENTED) https://github.com/rook/rook/blob/3e7e31fd3e24e8965fdc53eb8b78c021900eac65/design/ceph/object/bucketpolicy.md
- https://gitlab.com/open-infrastructure-labs/moc-cnv-sandbox/-/issues/54

cc @4n4nd @HumairAK @larsks

**Comment by larsks** [comment]
Can you tell me more about this request? 

Ceph's S3 implementation (Rados GW) already supports (and enforces) bucket policies. The Noobaa S3 service does as well, although in OCS 4.5 there were some bugs that I think are resolved in OCS 4.6. There is an external route to the S3 endpoints in both cases, but there are no external routes to Ceph (which at least in the MOC environment is typically only made available to hosts on directly connected subnets).

**Comment by 4n4nd** [comment]
@larsks could you give us an example on how to generate read only access keys for an `ObjectBucketClaim`?

**Comment by larsks** [comment]
@4n4nd you mean anonymous read-only access? Or read-only access associated with a particular access key?

**Comment by 4n4nd** [comment]
I think either should work

**Comment by larsks** [comment]
Since the OBC is provided by an S3 endpoint, you can just use S3-compatible tooling to set the policy associated with a bucket. For example, to set up anonymous read access, start with an OBC:

```
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: example-rgw
spec:
  generateBucketName: example
  storageClassName: ocs-storagecluster-ceph-rgw
```

Once that's created, retrieve the generated `Secret` and `ConfigMap` resources and use the resulting information to set `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` variable (or configure an Amazon-style credentials file).

Create a policy for the bucket, like this (replacing `BUCKET_NAME` with the actual name of the bucket returned in the `ConfigMap`):

```
{
  "Version":"2012-10-17",
  "Statement":[
    {
      "Sid":"PublicRead",
      "Effect":"Allow",
      "Principal": "*",
      "Action":["s3:GetObject", "s3:GetObjectVersion"],
      "Resource":["arn:aws:s3:::BUCKET_NAME/*"]
    }
  ]
}
```

Submit the bucket policy:

```
aws --endpoint https://BUCKET_HOST s3api put-bucket-policy --bucket BUCKET_NAME --policy file://./policy.json
```

(Where `BUCKET_HOST` and `BUCKET_NAME` are replaced with values from the `ConfigMap`)

Note that with OCS 4.5 the above will only work with buckets provided by the Ceph RGW endpoint; the Noobaa endpoint won't properly apply a policy like this to the bucket itself (it will allow read access to individual objects). I believe that's fixed in 4.6, but I haven't had the chance to verify that yet.

There are some docs [here](https://access.redhat.com/documentation/en-us/red_hat_openshift_container_storage/4.5/html/deploying_and_managing_openshift_container_storage_using_google_cloud/multicloud-object-gateway_gcp#bucket-policies-in-the-Multicloud-object-gateway).

**Comment by martinpovolny** [comment]
@larsks : but such permission setting gets lost as when the bucket is pre-provisioned, isn't it.

Unlike in the case of the Rook proposal.

**Comment by larsks** [comment]
@martinpovolny oh, the rook proposal would definitely an improvement once it gets implemented and lands in OpenShift.

**Comment by tumido** [comment]
@larsks is it possible to have multiple sets of credentials to a bucket? I know there's the original pair created when the bucket is provisioned... Is there a way to get additional creds?

**Comment by larsks** [comment]
@tumido it looks like the answer is efffectively "no".

It is actually possible to create new AWS credentials, but that requires admin access to the Ceph environment in order to run the `radosgw-admin` command. There is no API access to that feature right now.
