### ISSUE TITLE
Investigate options for a re-usable/generic service catalog (rather than re-inventing the wheel).

### ISSUE THREAD

**Issue by HumairAK** [operate-first/support#560]

**Comment by tumido** [comment]
Evaluating opensource options that serve similar purpose:

1. https://backstage.io/ (live demo: https://demo.backstage.io/, https://backstage.io/demos)
   - It has a Helm Chart + Kubernetes documentation
   - Service resources are YAMLs in Kubernetes-like format, however it seems it's not a CR (applies through config change, not through Kubernetes API)
   - Very complex and complete, full of features and plugins
   - Probably a steep learning curve due to complexity
   - CNCF incubating project (Same stage as Argo/KNative/Operator Framework...) 
2. https://kronicle.tech/ (live demo: https://demo.kronicle.tech/ )
   - It has a Helm Chart
   - Simpler configuration through config
   - More table-like tool than a visual dashboard
3. https://ortelius.io/ (formerly deployhub.com)
   - It has a Helm Chart
   - UX is not polished - not easy to navigate
   - Looks a bit dated

What would be nice but is not opensource/self-hosted:
- https://www.moment.dev/
- https://www.cortex.io/
- https://www.opslevel.com/
- https://www.getambassador.io/

Continuing with investigation.

**Comment by HumairAK** [comment]
#1 definitely looks a lot more polished 
> however it seems it's not a CR (applies through config change, not through Kubernetes API) 

I think this is fine, can the configs be something we store declaratively to roll out changes? 
Based on repo stats it seems very popular as well. 

#2 looks like it's still very new, and it's on 0.1.x still so not sure if we can expect much in terms of stability (also seems to have much lower adoption). _However_ if it gets the job done and is much easier/simple to maintain, then I think this is fine. 


The plugin support for #1 seems a lot more extensive, with prometheus/grafana specifically mentioned, that sounds big bonus.

**Comment by tumido** [comment]
Conclusion and plan on SD deployment going forward:

- We're gonna start with https://github.com/operate-first/operate-first.github.io/pull/57 and use that as a baseline for list of provided services
- In the meantime we start working on a Backstage deployment transforming the Helm Chart into a Kustomize based set of manifests or use their Kubernetes guide directly to achieve the same.
- We expect a bit bumpy road with current state of Backstage Kubernetes support according to plugin management, configuration changes and auth. If this experiment doesn't satisfy our needs we will move on to a different tool.

**Comment by tumido** [comment]
Reopening. Creating ADR for this.

**Comment by HumairAK** [comment]
Completed by: https://github.com/operate-first/blueprint/pull/106
