### ISSUE TITLE
Deploy experimental instance of Backstage

### ISSUE THREAD

**Issue by tumido** [operate-first/support#578]
As per https://github.com/operate-first/support/issues/560 we decided to try to adopt Backstage as our Service catalog. This issue is a request for ourselves to attempt to deploy Backstage to Operate First Community Cloud.

We should utilize either:
- https://backstage.io/docs/deployment/helm
- https://backstage.io/docs/deployment/k8s

**Comment by SamoKopecky** [comment]
- PR for catalog definitions files: https://github.com/operate-first/apps/pull/2030
- Temporary repo for the `backstage` code/deployments: https://github.com/samoKopecky/backstage-deployment

**Comment by tumido** [comment]
Question: The repo backstage-deployment you have.. can you explain what would be the appropriate next steps for this? It seems we need to host all the Backstage codebase somewhere, correct? Do you suggest to fork their repos and apply our config on top? Is that the right course of actions?

**Comment by SamoKopecky** [comment]
I don't think forking is a good idea since the official backstage [repo](https://github.com/backstage/backstage) is meant to be a repo for developing backstage and contains a lot of unnecessary code. 

What I've done in my temporary repo is that I created the very basic backstage app using the command `npx@backstage/create-app` and then uploaded this to the repo (more info [here](https://backstage.io/docs/getting-started/create-an-app)). This code base contains only the backend and the frontend of the backstage app.

In terms of keeping the code up to date with the latest backstage packages there is a convenient command in their cli 
```
yarn backstage-cli versions:bump
```
 which updates all the dependencies and backstage packages to the newest version of backstage.
 


> Question: The repo backstage-deployment you have.. can you explain what would be the appropriate next steps for this? It seems we need to host all the Backstage codebase somewhere, correct? Do you suggest to fork their repos and apply our config on top? Is that the right course of actions?

I would suggest using the created code from `npx@backstage/create-app` and using that as a separate repo. Even the backstage documentation suggests that this is a good approach for deploying your own instance of backstage.

**Comment by SamoKopecky** [comment]
I've done some more research on authentication and user management in backstage:
#### Users/teams from the operate-first org can be imported straight into backstage as users/groups.
- This will use the GitHub API to create users/groups in the backstage app but the authentication of users is not defined here.
- This also required GitHub integration which can be set up using a bot or a GitHub app.
- Link to [docs](https://backstage.io/docs/integrations/github/org)
#### Authentication
- Can be set up also via GitHub using a GitHub OAuth app.
- There also exists to allow guests in with no account, which we probably want.
- Link to [docs](https://backstage.io/docs/auth/github/provider)
#### Permissions for users can be defined via a permission policy in code
- The permissions defined by the service definitions files (for example the owners of services) don't automatically apply to components and so everyone can delete them.
- This can be corrected using the permission policy
- Link to [docs](https://backstage.io/docs/permissions/custom-rules) 

I also found another way we can import the service definition files, so right now we have two options.
1. Automatic discovery of definitions using the github-discovery plugin, this way each repo can have its own definitions files for a service or it can live in one repo ([docs](https://backstage.io/docs/integrations/github/discovery)).
2. Hardcoded link in a config that takes files from one central repository. This is the way is is implemented in the [PR](https://github.com/operate-first/apps/pull/2030) created in apps repo.

**Comment by HumairAK** [comment]
@SamoKopecky demo'd a experimental instance, both locally and on a dev cluster, it meets our mvp
