### ISSUE TITLE
Unable to spawn Jupyter Notebooks on Smaug

### ISSUE THREAD

**Issue by oindrillac** [operate-first/support#593]
### Describe the Problem

I am unable to spawn a jupyter notebook on the smaug cluster. Irrespective of the container size i select, I get errors such as the following 

```
Error: HTTP 500: Internal Server Error (Error in Authenticator.pre_spawn_start: ApiException (403) Reason: error HTTP response headers: HTTPHeaderDict({'Audit-Id': '1e7bc0b8-acf1-4466-9401-6d443beb4d6d', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'Warning': '299 - "spec.containers[0].env[17].name: duplicate name \\"MEM_LIMIT\\""', 'X-Kubernetes-Pf-Flowschema-Uid': '455b24cc-3b0e-4d7f-b9a0-ae84569826f1', 'X-Kubernetes-Pf-Prioritylevel-Uid': '08aa5218-91f5-42b2-abb6-cdd3a28cc286', 'Date': 'Tue, 21 Jun 2022 13:01:40 GMT', 'Content-Length': '331'}) HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"pods \"jupyterhub-nb-oindrillac\" is forbidden: exceeded quota: opf-jupyterhub-custom, requested: limits.cpu=3, used: limits.cpu=120, limited: limits.cpu=120","reason":"Forbidden","details":{"name":"jupyterhub-nb-oindrillac","kind":"pods"},"code":403} )
```

### Steps to Reproduce

1. Go to https://jupyterhub-opf-jupyterhub.apps.smaug.na.operate-first.cloud/
2. Select `Openshift CI Analysis Notebook Image` notebook image
3. Select "default", "small", "medium", or "large" cluster
4. Fails with the above error

### Expected behaviour

Should succesfully spawn jupyter lab

### Screenshots

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/32435206/174806667-be315542-a2d3-4268-8b22-8b00633590ab.png">

### Additional context

This has been only happening since the past week or so, sometimes i see this error when trying to spawn a large cluster and when i switch to small it works. 
Also one time i was seeing this error and when @chauhankaranraj shut down his server, i could spawn successfully. This seems like a resource limitation on smaug.

**Comment by HumairAK** [comment]
@oindrillac you're right this is due to the jupyterhub namespace being capped on resources. 

![image](https://user-images.githubusercontent.com/10904967/174808173-a37087c9-2180-4596-ad14-cb04968e900f.png)

Looks like we're capped on cpu/memory limits. Let's increase those. They are found here: https://github.com/operate-first/apps/blob/master/cluster-scope/base/core/namespaces/opf-jupyterhub/resourcequota.yaml#L7-L8

Let's increase `limits.cpu` to `140` and `limist.memory` to `800Gi` WDYT? 

@oindrillac is this something you'd be willing to contribute a PR for? 

Bonus points if you are willing to also add a small section at the bottom of our runbook on the steps you take [here](https://github.com/operate-first/apps/blob/master/docs/content/odh/jupyterhub/runbook.md).
