### ISSUE TITLE
mcliffor requests larger pvc

### ISSUE THREAD

**Issue by MichaelClifford** [operate-first/support#79]
### Questionnaire
Closes #67
1. **User details**:
mcliffor

2. **Desired resource change**:
 I would like my JH PVC limit to be increased from 2Gb to 20Gb 
---

If you don't want to wait for the maintainers to notice this issue, you can do the changes yourself. Please follow the [docs/user_profiles.md](https://github.com/operate-first/support/blob/main/docs/user_profiles.md) guide.

**Comment by martinpovolny** [comment]
@MichaelClifford : I wonder if the problem is related to pip cache size. If it's full of previous versions of packages as you work over a longer time it might need some purging.

I am not sure what is the best practice with Python but I assume there's a similar problem to other languages and environments.

**Comment by tumido** [comment]
@martinpovolny see: https://github.com/operate-first/support/issues/68 yes, it kinda is, we're trying to resolve it via `thamos` but that has problem with local packages: https://github.com/thoth-station/thamos/issues/728

**Comment by MichaelClifford** [comment]
@martinpovolny Yes, the pip cache size is definitely a problem at the moment. But I would also like to have more than 2Gb PVC in general for Data Science work.
